auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: bigbully
url: http://bigbully.github.io
feed: /atom.xml
author_info: <a href="http://weibo.com/bigbully">bigbully</a>
